apiVersion: apps/v1
kind: Deployment
metadata:
  name: uhsdif
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uhsdif
  template:
    metadata:
      labels:
        app: uhsdif
    spec:
      containers:
      - image: okteto.dev/uhsdif:latest
        name: uhsdif
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "27213ba3-01af-4006-bb39-9bb5fe259d4c"
        - name: Vless_Path
          value: "/vlqaz5"
        - name: Vmess_UUID
          value: "27213ba3-01af-4006-bb39-9bb5fe259d4c"
        - name: Vmess_Path
          value: "/vmqaz6"
        - name: Share_Path
          value: "/v2link"
